services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dmarket-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs

    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"

  watchtower:
    image: containrrr/watchtower
    container_name: dmarket-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --cleanup
    restart: always
