import statistics
from typing import List, Optional

class PAlgorsTradingStrategy:
    """
    Implements Statistical Arbitrage logic for the DMarket Bot.
    Generated by the Swarm (Core). Executed by the Bot.
    
    Logic:
    1. Tracks the spread between two correlated assets (e.g., AK-47 Redline FT vs MW).
    2. Calculates Z-Score (standard score) of the current spread.
    3. Signals entry when spread deviates significantly (> 2 sigma) from mean.
    """

    def __init__(self, entry_threshold: float = 2.0, exit_threshold: float = 0.0):
        self.entry_threshold = entry_threshold
        self.exit_threshold = exit_threshold

    def _calculate_spread_history(self, series_a: List[float], series_b: List[float]) -> List[float]:
        """Calculates the historical spread (Asset A - Asset B)."""
        # Assuming 1:1 hedge ratio for this MVP version
        return [a - b for a, b in zip(series_a, series_b)]

    def analyze_pAlgor(self, current_price_a: float, current_price_b: float, 
                     history_a: List[float], history_b: List[float]) -> str:
        """
        Determines the trading action based on Z-Score.
        Returns: 'LONG_A_SHORT_B', 'SHORT_A_LONG_B', 'EXIT', or 'HOLD'.
        """
        if len(history_a) != len(history_b) or len(history_a) < 10:
            return "HOLD (Insufficient Data)"

        spreads = self._calculate_spread_history(history_a, history_b)
        mean_spread = statistics.mean(spreads)
        stdev_spread = statistics.stdev(spreads)

        if stdev_spread == 0:
            return "HOLD (Zero Volatility)"

        current_spread = current_price_a - current_price_b
        z_score = (current_spread - mean_spread) / stdev_spread

        # Mean Reversion Logic
        if z_score > self.entry_threshold:
            # Spread is too high (A is expensive, B is cheap) -> Sell A, Buy B
            return "SHORT_A_LONG_B"
        elif z_score < -self.entry_threshold:
            # Spread is too low (A is cheap, B is expensive) -> Buy A, Sell B
            return "LONG_A_SHORT_B"
        elif abs(z_score) <= self.exit_threshold:
            return "EXIT"
        
        return "HOLD"
