"""initial_v2_numeric

Revision ID: 94a4311890ba
Revises: 
Create Date: 2026-02-09 17:52:59.209851

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy.types as types

class SQLiteUUID(types.TypeDecorator):
    impl = types.CHAR(36)
    cache_ok = True

    def process_bind_param(self, value, dialect):
        if value is None:
            return value
        return str(value)

    def process_result_value(self, value, dialect):
        if value is None:
            return value
        return value


# revision identifiers, used by Alembic.
revision: str = '94a4311890ba'
down_revision: str | None = None
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    """Upgrade database schema.

    This function applies schema changes to the database.
    Add detailed comments for complex operations.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_log',
    sa.Column('id', SQLiteUUID(), nullable=False),
    sa.Column('user_id', SQLiteUUID(), nullable=True),
    sa.Column('command', sa.String(length=100), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_command_log'))
    )
    with op.batch_alter_table('command_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_command_log_command'), ['command'], unique=False)
        batch_op.create_index(batch_op.f('ix_command_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_command_log_user_id'), ['user_id'], unique=False)

    op.create_table('events',
    sa.Column('id', SQLiteUUID(), nullable=False),
    sa.Column('user_id', SQLiteUUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_user_id'), ['user_id'], unique=False)

    op.create_table('market_data',
    sa.Column('id', SQLiteUUID(), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('game', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('suggested_price_usd', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('price_change_24h', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('volume_24h', sa.Integer(), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_data'))
    )
    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_data_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_data_data_source'), ['data_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_data_game'), ['game'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_data_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_data_item_name'), ['item_name'], unique=False)

    op.create_table('market_data_cache',
    sa.Column('id', SQLiteUUID(), nullable=False),
    sa.Column('cache_key', sa.String(length=500), nullable=False),
    sa.Column('game', sa.String(length=50), nullable=False),
    sa.Column('item_hash_name', sa.String(length=500), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_data_cache'))
    )
    with op.batch_alter_table('market_data_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_data_cache_cache_key'), ['cache_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_market_data_cache_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_data_cache_game'), ['game'], unique=False)

    op.create_table('pending_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(length=255), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('game', sa.String(length=50), nullable=False),
    sa.Column('buy_price', sa.Float(), nullable=False),
    sa.Column('min_sell_price', sa.Float(), nullable=False),
    sa.Column('target_sell_price', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('offer_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('adjustments_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('listed_at', sa.DateTime(), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_trades'))
    )
    with op.batch_alter_table('pending_trades', schema=None) as batch_op:
        batch_op.create_index('idx_pending_trades_game_status', ['game', 'status'], unique=False)
        batch_op.create_index('idx_pending_trades_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_trades_asset_id'), ['asset_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_pending_trades_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_trades_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_trades_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_trades_user_id'), ['user_id'], unique=False)

    op.create_table('price_alerts',
    sa.Column('id', SQLiteUUID(), nullable=False),
    sa.Column('user_id', SQLiteUUID(), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=True),
    sa.Column('market_hash_name', sa.String(length=500), nullable=True),
    sa.Column('game', sa.String(length=50), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('triggered', sa.Boolean(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_alerts'))
    )
    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_alerts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('game', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_targets'))
    )
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_targets_game'), ['game'], unique=False)
        batch_op.create_index(batch_op.f('ix_targets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_targets_target_id'), ['target_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_targets_user_id'), ['user_id'], unique=False)

    op.create_table('telegram_persistence',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_telegram_persistence'))
    )
    op.create_table('trade_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_type', sa.String(length=50), nullable=False),
    sa.Column('item_title', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('game', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('trade_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_history'))
    )
    with op.batch_alter_table('trade_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_history_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_history_user_id'), ['user_id'], unique=False)

    op.create_table('trading_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('max_trade_value', sa.Float(), nullable=True),
    sa.Column('daily_limit', sa.Float(), nullable=True),
    sa.Column('min_profit_percent', sa.Float(), nullable=True),
    sa.Column('strategy', sa.String(length=50), nullable=True),
    sa.Column('auto_trading_enabled', sa.Integer(), nullable=True),
    sa.Column('games_enabled', sa.JSON(), nullable=True),
    sa.Column('notifications_enabled', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trading_settings'))
    )
    with op.batch_alter_table('trading_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_settings_user_id'), ['user_id'], unique=True)

    op.create_table('user_settings',
    sa.Column('id', SQLiteUUID(), nullable=False),
    sa.Column('user_id', SQLiteUUID(), nullable=False),
    sa.Column('default_game', sa.String(length=50), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('price_alerts_enabled', sa.Boolean(), nullable=True),
    sa.Column('arbitrage_alert_enabled', sa.Boolean(), nullable=True),
    sa.Column('min_profit_percent', sa.Float(), nullable=True),
    sa.Column('preferred_currency', sa.String(length=10), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_settings'))
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_settings_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', SQLiteUUID(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('dmarket_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('dmarket_secret_key_encrypted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_banned'), ['is_banned'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema.

    This function reverts schema changes from the upgrade.
    Ensure this is always the inverse of upgrade().
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_users_is_banned'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))

    op.drop_table('users')
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_user_id'))

    op.drop_table('user_settings')
    with op.batch_alter_table('trading_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_settings_user_id'))

    op.drop_table('trading_settings')
    with op.batch_alter_table('trade_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_trade_history_status'))

    op.drop_table('trade_history')
    op.drop_table('telegram_persistence')
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_targets_user_id'))
        batch_op.drop_index(batch_op.f('ix_targets_target_id'))
        batch_op.drop_index(batch_op.f('ix_targets_status'))
        batch_op.drop_index(batch_op.f('ix_targets_game'))

    op.drop_table('targets')
    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_price_alerts_is_active'))

    op.drop_table('price_alerts')
    with op.batch_alter_table('pending_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_trades_user_id'))
        batch_op.drop_index(batch_op.f('ix_pending_trades_status'))
        batch_op.drop_index(batch_op.f('ix_pending_trades_offer_id'))
        batch_op.drop_index(batch_op.f('ix_pending_trades_item_id'))
        batch_op.drop_index(batch_op.f('ix_pending_trades_asset_id'))
        batch_op.drop_index('idx_pending_trades_status_created')
        batch_op.drop_index('idx_pending_trades_game_status')

    op.drop_table('pending_trades')
    with op.batch_alter_table('market_data_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_data_cache_game'))
        batch_op.drop_index(batch_op.f('ix_market_data_cache_expires_at'))
        batch_op.drop_index(batch_op.f('ix_market_data_cache_cache_key'))

    op.drop_table('market_data_cache')
    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_data_item_name'))
        batch_op.drop_index(batch_op.f('ix_market_data_item_id'))
        batch_op.drop_index(batch_op.f('ix_market_data_game'))
        batch_op.drop_index(batch_op.f('ix_market_data_data_source'))
        batch_op.drop_index(batch_op.f('ix_market_data_created_at'))

    op.drop_table('market_data')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_events_created_at'))

    op.drop_table('events')
    with op.batch_alter_table('command_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_command_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_command_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_command_log_command'))

    op.drop_table('command_log')
    # ### end Alembic commands ###



